version: "3.8"
services:

  app_proxy:
    environment:
      # <app-id>_<web-container-name>_1
      # e.g. 'btc-rpc-explorer_web_1'
      # Note that the '_1' at the end is needed
      APP_HOST: spookee-nginxui_server_1
      APP_PORT: 80

  server:
    image: uozi/nginx-ui:2.0.0-beta.41
    environment:
      LANG: en
      TZ: Europer/Berlin
    #container_name: nginx-ui
    volumes:
      - "${APP_NGINXUI_NGINX_DIR}:/etc/nginx"
      - "${APP_NGINXUI_UI_DIR}:/etc/nginx-ui"
      - "${APP_NGINXUI_WWW_DIR}:/var/www"
    #ports:
    #  - "${APP_NGINXUI_UI_PORT}:80/tcp"
    restart: unless-stopped

  #nginx:
  #  image: nginx:1.27.3
  #  container_name: nginx_proxy
  #  environment:
  #    TZ: Europe/Berlin
  #  volumes:
  #    - "${APP_NGINXUI_NGINX_DIR}:/etc/nginx"
  #    - "${APP_NGINXUI_WWW_DIR}:/var/www"
  #  ports:
  #    - "4080:80"
  #    - "4443:443"
