version: '3.8'

services:

  pd0:
    container_name: surrealdb-pd0
    image: pingcap/pd:v6.1.0
    ports:
      - "2379"
    volumes:
      - "${APP_SURREALDB_DATA_DIR}/data:/data"
      - "${APP_SURREALDB_DATA_DIR}/logs:/logs"
    command:
      - --name=pd0
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd0:2379
      - --advertise-peer-urls=http://pd0:2380
      - --initial-cluster=pd0=http://pd0:2380
      - --data-dir=/data/pd0
      - --log-file=/logs/pd0.log
    restart: on-failure

  tikv0:
    container_name: surrealdb-tikv0
    image: pingcap/tikv:v6.1.0
    volumes:
      - "${APP_SURREALDB_DATA_DIR}/data:/data"
      - "${APP_SURREALDB_DATA_DIR}/logs:/logs"
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv0:20160
      - --data-dir=/data/tikv0
      - --pd=pd0:2379
      - --log-file=/logs/tikv0.log
    depends_on:
      - "pd0"
    restart: on-failure

#  prometheus:
#    container_name: surrealdb-prometheus
#    image: prom/prometheus:v2.2.1
#    user: root
#    command:
#      - --log.level=error
#      - --storage.tsdb.path=/data/prometheus
#      - --config.file=/etc/prometheus/prometheus.yml
#    #ports:
#    #  - "9090:9090"
#    volumes:
#      - "${APP_SURREALDB_DATA_DIR}/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
#      - "${APP_SURREALDB_DATA_DIR}/config/pd.rules.yml:/etc/prometheus/pd.rules.yml:ro"
#      - "${APP_SURREALDB_DATA_DIR}/config/tikv.rules.yml:/etc/prometheus/tikv.rules.yml:ro"
#      - "${APP_SURREALDB_DATA_DIR}/config/tidb.rules.yml:/etc/prometheus/tidb.rules.yml:ro"
#      - "${APP_SURREALDB_DATA_DIR}/data:/data"
#    restart: unless-stopped
#    profiles:
#      - monitoring

#  grafana:
#    image: grafana/grafana:6.0.1
#    container_name: surrealdb-grafana
#    user: "0"
#    environment:
#      GF_LOG_LEVEL: error
#      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
#      GF_PATHS_CONFIG: /etc/grafana/grafana.ini
#    volumes:
#      - "${APP_SURREALDB_DATA_DIR}/config/grafana:/etc/grafana"
#      - "${APP_SURREALDB_DATA_DIR}/config/dashboards:/tmp/dashboards"
#      - "${APP_SURREALDB_DATA_DIR}/data/grafana:/var/lib/grafana"
#    #ports:
#    #  - "3000:3000"
#    restart: unless-stopped
#    profiles:
#      - monitoring

  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    restart: unless-stopped
    ports:
      - "${APP_SURREALDB_PORT}:8000"
    command: 
      - start
      - --log=trace
      - --user=root
      - --pass=${APP_PASSWORD}
      - tikv://pd0:2379
    depends_on:
      - tikv0
    restart: always    